// src/components/coacting-events/Output.tsx
import { For, Show } from 'solid-js';
import { store } from './store';

export const Output = () => {
  return (
    <Show when={store.result}>
      <p>{store.result?.events.length}件のイベントが見つかりました。</p>
      <ul class="d-list">
        <For each={store.result?.events}>
          {(event) => (
            <li class="d-list-row">
              <div>
                <a
                  href={`https://www.eventernote.com${event.href}`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {event.name}
                </a>
                <div class="text-xs">{event.date}</div>
                <div class="text-xs">{event.place}</div>
              </div>
            </li>
          )}
        </For>
      </ul>
    </Show>
  );
};

// components/coacting-events/Output.vue
<template>
  <p v-if="store.result">
    {{ store.result.length }}件のイベントが見つかりました。
  </p>
  <ul>
    <li v-for="event in store.result">
      <a
        :href="'https://www.eventernote.com' + event.href"
        target="_blank"
        rel="noopener noreferrer"
        >{{ event.name }}</a
      >
    </li>
  </ul>
</template>

<script setup lang="ts">
import { store } from "../../store/coacting-events";
</script>
