// src/components/coacting-events/Input.svelte
<script lang="ts">
import { onMount } from 'svelte';
import { store } from './store.svelte';

const ACTOR_NAMES_KEY = 'coactingEvents.actorNames';
let actorNames = $state(['', '']);
const canNotSearch = $derived(actorNames.some((v) => !v));

const saveActorNames = () => {
  localStorage.setItem(ACTOR_NAMES_KEY, JSON.stringify(actorNames));
};

onMount(() => {
  const storedActorNames = localStorage.getItem(ACTOR_NAMES_KEY);
  if (storedActorNames) {
    actorNames = JSON.parse(storedActorNames);
  }
});
</script>

<form
  class="d-card p-2 gap-4"
  onsubmit={async (e) => {
    e.preventDefault();
    await store.search(new FormData(e.currentTarget));
  }}
>
  <input type="hidden" name="useCache" value="true" />

  {#each actorNames as actorName, index}
    <label class="d-floating-label">
      <span>{`出演者名${index + 1}`}</span>
      <input
        class="d-input"
        type="text"
        name="actorNames"
        placeholder={`出演者名${index + 1}`}
        bind:value={actorNames[index]}
        onblur={() => {
          actorNames[index] = actorName.trim();
          saveActorNames();
        }}
      />
    </label>
  {/each}

  <div class="d-card-actions">
    <button
      class="d-btn d-btn-primary"
      type="submit"
      disabled={store.loading || canNotSearch}
    >
      検索
      {#if store.loading}
        <span class="d-loading d-loading-spinner"></span>
      {/if}
    </button>
    <button
      class="d-btn d-btn-secondary"
      type="button"
      disabled={store.loading}
      onclick={() => {
        actorNames.push('');
        saveActorNames();
      }}
    >
      追加
    </button>
    <button
      class="d-btn d-btn-warning"
      type="button"
      disabled={store.loading || actorNames.length <= 1}
      onclick={() => {
        actorNames.pop();
        saveActorNames();
      }}
    >
      削除
    </button>
  </div>

  {#if store.error}
    {@const error = store.error}
    <div class="d-alert d-alert-error" role="alert">
      <span>
        {error.code !== 'INTERNAL_SERVER_ERROR' && error.message
          ? error.message
          : '予期せぬエラーが発生しました。'}
      </span>
    </div>
  {/if}
</form>

// src/components/attended-events/Input.tsx
import { Show } from 'solid-js';
import { error, loading, search, setInputStore, useInputStore } from './store';

export const Input = () => {
  const inputStore = useInputStore();
  const canNotSearch = () => !inputStore.userId;

  return (
    <form
      onSubmit={async (e) => {
        e.preventDefault();
        await search(new FormData(e.currentTarget));
      }}
      class="d-card p-2 gap-4"
    >
      <input type="hidden" name="useCache" value="true" />

      <label class="d-floating-label">
        <span>ユーザーID</span>
        <input
          type="text"
          name="userId"
          placeholder="ユーザーID"
          value={inputStore.userId}
          onInput={(e) => {
            setInputStore('userId', e.target.value);
          }}
          class="d-input"
        />
      </label>

      <label class="d-floating-label">
        <span>出演者名</span>
        <input
          type="text"
          name="actorName"
          placeholder="出演者名（オプション）"
          value={inputStore.actorName ?? ''}
          onInput={(e) => {
            setInputStore('actorName', e.target.value);
          }}
          class="d-input"
        />
      </label>

      <label class="d-floating-label">
        <span>会場名</span>
        <input
          type="text"
          name="placeName"
          placeholder="会場名（オプション）"
          value={inputStore.placeName ?? ''}
          onInput={(e) => {
            setInputStore('placeName', e.target.value);
          }}
          class="d-input"
        />
      </label>

      <div class="d-card-actions">
        <button
          type="submit"
          disabled={loading() || canNotSearch()}
          class="d-btn d-btn-primary"
        >
          検索
          <Show when={loading()}>
            <span class="d-loading d-loading-spinner" />
          </Show>
        </button>
      </div>

      <Show when={error()} keyed>
        {(error) => (
          <div role="alert" class="d-alert d-alert-error">
            <span>
              {error.code !== 'INTERNAL_SERVER_ERROR' && error.message
                ? error.message
                : '予期せぬエラーが発生しました。'}
            </span>
          </div>
        )}
      </Show>
    </form>
  );
};
