// src/components/attendance-statistics/Output.svelte
<script lang="ts">
import { navigate } from 'astro:transitions/client';
import { ScanSearchIcon } from 'lucide-svelte';
import { INPUT_DATA_KEY } from '../attended-events/Input.svelte';
import { store as attendedEventsStore } from '../attended-events/store.svelte';
import Table from '../common/Table.svelte';
import { store } from './store.svelte';

type ItemCount = readonly [string, number];
</script>

{#if store.data}
  {@const {userId, actorCounts, placeCounts} = store.data}
  <div role="tablist" class="d-tabs d-tabs-border">
    <input
      class="d-tab"
      type="radio"
      role="tab"
      name="tabs"
      aria-label="出演者"
      checked
    />
    <div class="d-tab-content">
      {#snippet actorHeader()}
        <th></th>
        <th class="text-center">出演者名</th>
        <th class="text-right">参加数</th>
        <th class="text-center">検索</th>
      {/snippet}

      {#snippet actorRow([actorName, count]: ItemCount, index: number)}
        <th>{index + 1}</th>
        <td class="text-center">{actorName}</td>
        <td class="text-right">{count}</td>
        <td class="text-center w-16">
          <button
            class="d-btn d-btn-ghost d-btn-xs d-btn-square"
            type="button"
            disabled={attendedEventsStore.loading}
            onclick={async () => {
            sessionStorage.setItem(
              INPUT_DATA_KEY,
              JSON.stringify({
                userId,
                actorName,
                placeName: '',
              }),
            );
            await navigate('/attended-events/');
          }}
          >
            <ScanSearchIcon size={20} />
          </button>
        </td>
      {/snippet}

      <Table
        items={actorCounts}
        header={actorHeader}
        row={actorRow}
        copyText={() => actorCounts.map((data) => data.join(',')).join('\n')}
      />
    </div>

    <input
      class="d-tab"
      type="radio"
      role="tab"
      name="tabs"
      aria-label="会場"
    />
    <div class="d-tab-content">
      {#snippet placeHeader()}
        <th></th>
        <th class="text-center">会場名</th>
        <th class="text-right">参加数</th>
        <td class="text-center">検索</td>
      {/snippet}

      {#snippet placeRow([placeName, count]: ItemCount, index: number)}
        <th scope="row">{index + 1}</th>
        <td class="text-center">{placeName}</td>
        <td class="text-right">{count}</td>
        <td class="text-center w-16">
          <button
            class="d-btn d-btn-ghost d-btn-xs d-btn-square"
            type="button"
            disabled={attendedEventsStore.loading}
            onclick={async () => {
            sessionStorage.setItem(
              INPUT_DATA_KEY,
              JSON.stringify({
                userId,
                actorName: '',
                placeName,
              }),
            );
            await navigate('/attended-events/');
          }}
          >
            <ScanSearchIcon size={20} />
          </button>
        </td>
      {/snippet}

      <Table
        items={placeCounts}
        header={placeHeader}
        row={placeRow}
        copyText={() => placeCounts.map((data) => data.join(',')).join('\n')}
      />
    </div>
  </div>
{/if}

// src/components/attendance-statistics/Output.tsx
import { navigate } from 'astro:transitions/client';
import { ScanSearchIcon } from 'lucide-solid';
import { For, Show } from 'solid-js';
import type { OutputData } from '../../actions/attendanceStatistics';
import { loading, searchFromStatistics } from '../attended-events/store';
import { ClipboardCopy } from '../common/ClipboardCopy';
import { Pagination } from '../common/Pagination';
import { usePagination } from '../common/usePagination';
import { output } from './store';

export const Output = () => (
  <Show when={output()}>{(output) => <OutputContent {...output()} />}</Show>
);

const OutputContent = (output: OutputData) => {
  const {
    paginationProps: actorPaginationProps,
    pagedItems: pagedActorCounts,
  } = usePagination(() => output.actorCounts);
  const {
    paginationProps: placePaginationProps,
    pagedItems: pagedPlaceCounts,
  } = usePagination(() => output.placeCounts);

  return (
    <div role="tablist" class="d-tabs d-tabs-border">
      <input
        class="d-tab"
        type="radio"
        role="tab"
        name="tabs"
        aria-label="出演者"
        checked
      />
      <div class="d-tab-content">
        <div class="d-card p-2 gap-4">
          <ClipboardCopy
            getText={() =>
              output.actorCounts.map((data) => data.join(',')).join('\n')
            }
          />
          <Pagination {...actorPaginationProps()} />
          <div class="overflow-x-auto">
            <table class="d-table">
              <thead>
                <tr>
                  <th />
                  <th class="text-center">出演者名</th>
                  <th class="text-right">参加数</th>
                  <th class="text-center">検索</th>
                </tr>
              </thead>
              <tbody>
                <For each={pagedActorCounts()}>
                  {({ item: [actorName, count], index }) => (
                    <tr>
                      <th>{index + 1}</th>
                      <td class="text-center">{actorName}</td>
                      <td class="text-right">{count}</td>
                      <td class="text-center w-16">
                        <button
                          class="d-btn d-btn-ghost d-btn-xs d-btn-square"
                          type="button"
                          disabled={loading()}
                          onClick={async () => {
                            await navigate('/attended-events/');
                            await searchFromStatistics({
                              userId: output.userId,
                              actorName,
                              placeName: '',
                            });
                          }}
                        >
                          <ScanSearchIcon size={20} />
                        </button>
                      </td>
                    </tr>
                  )}
                </For>
              </tbody>
            </table>
          </div>
          <Pagination {...actorPaginationProps()} />
        </div>
      </div>

      <input
        class="d-tab"
        type="radio"
        role="tab"
        name="tabs"
        aria-label="会場"
      />
      <div class="d-tab-content">
        <div class="d-card p-2 gap-4">
          <ClipboardCopy
            getText={() =>
              output.placeCounts.map((data) => data.join(',')).join('\n')
            }
          />
          <Pagination {...placePaginationProps()} />
          <div class="overflow-x-auto">
            <table class="d-table">
              <thead>
                <tr>
                  <th />
                  <th class="text-center">会場名</th>
                  <th class="text-right">参加数</th>
                  <td class="text-center">検索</td>
                </tr>
              </thead>
              <tbody>
                <For each={pagedPlaceCounts()}>
                  {({ item: [placeName, count], index }) => (
                    <tr>
                      <th scope="row">{index + 1}</th>
                      <td class="text-center">{placeName}</td>
                      <td class="text-right">{count}</td>
                      <td class="text-center w-16">
                        <button
                          class="d-btn d-btn-ghost d-btn-xs d-btn-square"
                          type="button"
                          disabled={loading()}
                          onClick={async () => {
                            await navigate('/attended-events/');
                            await searchFromStatistics({
                              userId: output.userId,
                              actorName: '',
                              placeName,
                            });
                          }}
                        >
                          <ScanSearchIcon size={20} />
                        </button>
                      </td>
                    </tr>
                  )}
                </For>
              </tbody>
            </table>
          </div>
          <Pagination {...placePaginationProps()} />
        </div>
      </div>
    </div>
  );
};
