// src/components/common/EventList.tsx
import { type Component, For } from 'solid-js';
import type { Event } from '../../types/event';
import { Pagination } from './Pagination';
import { usePagination } from './usePagination';

type EventListProps = {
  events: ReadonlyArray<Event>;
};

export const EventList: Component<EventListProps> = (props) => {
  const { paginationProps, pagedItems } = usePagination(() => props.events);

  return (
    <div class="d-card p-2 gap-4">
      <p>{props.events.length}件のイベントが見つかりました。</p>
      <Pagination {...paginationProps()} />
      <ul class="d-list">
        <For each={pagedItems()}>
          {({ item: event }) => (
            <li class="d-list-row">
              <div>
                <h4>
                  <a
                    class="d-link d-link-hover"
                    href={`https://www.eventernote.com${event.href}`}
                    target="_blank"
                    rel="noreferrer"
                  >
                    {event.name}
                  </a>
                </h4>
                <div class="text-xs">{event.date}</div>
                <div class="text-xs">{event.place}</div>
              </div>
            </li>
          )}
        </For>
      </ul>
      <div class="d-card-actions justify-center">
        <Pagination {...paginationProps()} />
      </div>
    </div>
  );
};

// src/components/common/EventList.svelte
<script lang="ts">
import type { Event } from '../../types/event';
import Pagination from './Pagination.svelte';
import { usePagination } from './usePagination.svelte';

type Props = {
  events: ReadonlyArray<Event>;
};

const { events }: Props = $props();
const pagination = usePagination(() => events);
</script>

<div class="d-card p-2 gap-4">
  <p>{events.length}件のイベントが見つかりました。</p>
  <Pagination
    totalPages={pagination.totalPages}
    bind:currentPage={pagination.currentPage}
  />
  <ul class="d-list">
    {#each pagination.pagedItems as { item: event }}
      <li class="d-list-row">
        <div>
          <h4>
            <a
              class="d-link d-link-hover"
              href={`https://www.eventernote.com${event.href}`}
              target="_blank"
              rel="noreferrer"
            >
              {event.name}
            </a>
          </h4>
          <div class="text-xs">{event.date}</div>
          <div class="text-xs">{event.place}</div>
        </div>
      </li>
    {/each}
  </ul>
  <Pagination
    totalPages={pagination.totalPages}
    bind:currentPage={pagination.currentPage}
  />
</div>
