// src/components/coacting-events/Input.tsx
import { ConvexHttpClient } from 'convex/browser';
import { ConvexError } from 'convex/values';
import {
  Index,
  Show,
  createEffect,
  createResource,
  createSignal,
} from 'solid-js';
import { createStore } from 'solid-js/store';
import { api } from '../../../convex/_generated/api';
import type { Request } from '../../../convex/coactingEvents';
import { setResponse } from './store';

export const Input = () => {
  const [actorNames, setActorNames] = createStore(['', '']);
  const canNotSearch = () => actorNames.some((name) => !name);

  const client = new ConvexHttpClient(import.meta.env.PUBLIC_CONVEX_URL);
  const [request, setRequest] = createSignal<Request>();
  const [responseResource] = createResource(request, (request) =>
    client.action(api.coactingEvents.search, request),
  );

  createEffect(() => {
    setResponse(responseResource.latest);
  });

  return (
    <>
      <div>
        <Index each={actorNames}>
          {(actorName, index) => (
            <input
              name={`actorName${index + 1}`}
              type="text"
              value={actorName()}
              onInput={(e) => {
                setActorNames(index, e.target.value);
              }}
              placeholder={`出演者${index + 1}`}
              class="d-input mt-3 w-full max-w-md"
            />
          )}
        </Index>
      </div>
      <div class="mt-3">
        <button
          type="button"
          onClick={() => {
            setRequest({ actorNames });
          }}
          disabled={responseResource.loading || canNotSearch()}
          class="d-btn d-btn-primary"
        >
          検索
          <Show when={responseResource.loading}>
            <span class="d-loading d-loading-spinner" />
          </Show>
        </button>
        <button
          type="button"
          onClick={() => {
            setActorNames((names) => [...names, '']);
          }}
          disabled={responseResource.loading}
          class="d-btn d-btn-secondary ml-3"
        >
          追加
        </button>
        <button
          type="button"
          onClick={() => {
            setActorNames((names) => names.slice(0, -1));
          }}
          disabled={responseResource.loading || actorNames.length <= 1}
          class="d-btn d-btn-warning ml-3"
        >
          削除
        </button>
      </div>
      <Show when={responseResource.error} keyed>
        {(error) => (
          <div role="alert" class="d-alert d-alert-error mt-3">
            <span>
              {error instanceof ConvexError
                ? error.data
                : '予期せぬエラーが発生しました。'}
            </span>
          </div>
        )}
      </Show>
    </>
  );
};

// src/components/coacting-events/Input.vue
<template>
  <div v-for="(_, index) in actorNames">
    <input
      v-model="actorNames[index]"
      type="text"
      class="d-input mt-3 w-full max-w-md"
      :placeholder="'出演者' + (index + 1)"
    />
  </div>
  <div class="mt-3">
    <button
      @click="searchCoactingEvents"
      :disabled="loading || canNotSearch"
      class="d-btn d-btn-primary"
    >
      検索
      <span v-if="loading" class="d-loading d-loading-spinner"></span>
    </button>
    <button
      @click="actorNames.push('')"
      :disabled="loading"
      class="d-btn d-btn-secondary ml-3"
    >
      追加
    </button>
    <button
      @click="actorNames.pop()"
      :disabled="loading || actorNames.length <= 1"
      class="d-btn d-btn-warning ml-3"
    >
      削除
    </button>
  </div>
  <div v-show="errorMessage" role="alert" class="d-alert d-alert-error mt-3">
    <span>{{ errorMessage }}</span>
  </div>
</template>

<script setup lang="ts">
import { ConvexHttpClient } from 'convex/browser';
import { ConvexError } from 'convex/values';
import * as Vue from 'vue';
import { api } from '../../../convex/_generated/api';
import { events, actorNames, errorMessage, loading } from './store';

const canNotSearch = Vue.computed(() => actorNames.value.some((v) => !v));
const searchCoactingEvents = () => {
  loading.value = true;
  errorMessage.value = undefined;
  new ConvexHttpClient(import.meta.env.PUBLIC_CONVEX_URL)
    .action(api.coactingEvents.search, {
      actorNames: actorNames.value,
    })
    .then((result) => {
      events.value = result;
    })
    .catch((e) => {
      console.error(e);
      errorMessage.value =
        e instanceof ConvexError ? e.data : '予期せぬエラーが発生しました。';
    })
    .finally(() => {
      loading.value = false;
    });
};
</script>
